### PR TITLE
Pull taskgraph from pypi

### PR DESCRIPTION
**Pull request by hneiva**

### CODE REVIEW

**Review by escapewindow — CHANGES_REQUESTED** [review]
Looks like we need a requirements.txt here.

**Review by escapewindow — APPROVED** [review]

**Comment by escapewindow** [comment]
I think the alternative here is to push the latest from xpi-manifest to this repo -- last I checked, I think that should work, and the 2 repos stay more in sync.

**Comment by hneiva** [comment]
> I think the alternative here is to push the latest from xpi-manifest to this repo -- last I checked, I think that should work, and the 2 repos stay more in sync.

🤔 I like that! Anything I should do before pushing?

**Comment by escapewindow** [comment]
Just make sure no one's using it, pretty sure you're in the clear.
I basically added the production remote to my staging clone, `git fetch production && git checkout production/main && git checkout -B main && git push` or similar.

**Comment by gabrielBusta** [comment]
I forced pushed upstream main onto main

**Pull request closed without merging**
